version: "3.0"

services:
  postgres:
    image: postgres:14-alpine
    container_name: mimimi_db
    environment:
      POSTGRES_DB: "mimimimetr"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/var/data
    ports:
      - "5432:5432"

  mimimi:
    build:
      context: .
    container_name: "mimimi"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
