drop table if exists pairs cascade;

create table pairs
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY,
    cat_one_id int8 NOT NULL,
    cat_two_id int8 NOT NULL,
    constraint fk_cat_1 foreign key (cat_one_id) references cat,
    constraint fk_cat_2 foreign key (cat_two_id) references cat,
    constraint unique_pair UNIQUE (cat_one_id, cat_two_id),
    primary key (id)
);