drop table if exists user_pairs_votes cascade;

create table user_pairs_votes
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY,
    pairs_id     int8    not null,
    user_session varchar not null,
    cat_id       int8,
    constraint fk_pairs foreign key (pairs_id) references pairs,
    constraint fk_cat foreign key (cat_id) references cat,
    constraint unique_votes UNIQUE (pairs_id, user_session),
    primary key (id)
);